config/routes.rb
Rails.application.routes.draw do
  
  resources :wikis
  resources :charges, only: [:new, :create]
 
   devise_for :users
   
  get 'about' => 'welcome#about'
  get 'downgrade' => 'users#downgrade'
    
   root to: 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis

  after_initialize :set_role

   def admin?
   role == 'admin'
 end
 
 def premium?
   role == 'premium'
 end

  def set_role
    self.role  ||= 'standard'   
  end        

  def private_allowed?
    role == 'admin' || role == 'premium'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  scope :visible_to, -> (user) { user && ((user.role == 'premium') || (user.role == 'admin')) ? all : where("private IS NULL or private = ?", false)  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

   rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end
 
   def after_sign_in_path_for(resource)
    wikis_path #your path
  end

   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController 

def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: 15_00
   }
 end


def create
 
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 29_95,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )
 
   flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to root_path(current_user) # or wherever
   # Upgrade the user account to 'premium' from standard
   current_user.role = 'premium'
   current_user.save



 # Stripe will send back CardErrors, with friendly messages
 # when something goes wrong.
 # This `rescue block` catches and displays those errors.
 rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
 end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade 
    current_user.update_attribute(:role, 'standard')
    current_user.wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
     redirect_to root_path
   end

  private

    def user_params
      params.require(:user).permit(:name, :role)
    end 

    def wiki_params(wiki)
      params.require(:wiki).permit(:private)
    end 
end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.visible_to(current_user)
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Your wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     if @wiki.update_attributes(params.require(:wiki).permit(:title, :body))
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :edit
     end
   end

  private

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper

def markdown_to_html(markdown)
  renderer = Redcarpet::Render::HTML.new
  extensions = {fenced_code_blocks: true}
  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  (redcarpet.render markdown).html_safe
end

  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<% unless current_user.premium? %> 
 <%= form_tag charges_path do %>
   <h1><strong>Upgrade to Premium!</strong></h1>
   <h3> Join the growing ranks of Blocipedia's elite Premium members! With a Premium account, you'll be able to create your own private wikis, select collaborators, and collaborate on other private wikis. You'll also be the first to hear about special Blocipedia events near you! For a limited time, upgrade your account with a one-time payment of just $15!</h3>
 </br>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" data-email="<%= current_user.email %>" ></script>
 <% end %>

<% else %>
<h2>Downgrade Account</h2>
<h4><br>Are you sure you want to lose premium acccess to Blocipedia? <br><br>If you downgrade your account, your private wikis will become public.
</h4>
<br>
<%= link_to "Yes, downgrade my account", downgrade_path, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to downgrade and make all your wikis public?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
   <ul class ="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>

         <div class="pull-right user-info">
           <% if current_user  %>
              Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! | 

              <% if current_user.role == 'standard' %>
                <%= link_to "Upgrade to Premium", new_charge_path %> |
              <% end %>
              
              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                          
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
         
   </ul>

   <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>

  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Hello There</h1>
<p><iframe width="900" height="500" src="https://www.youtube.com/embed/T-MUWJWqOv0" frameborder="0" allowfullscreen></iframe></p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron" >
  <div class="container">

  <h1>Bloccipedia</h1>
  <p>Blocipedia makes your life Easy</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-danger' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-danger' %> today!
  </p>
</div>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Create your Wiki</h2>
    <p>Bloccit will deliver food and water to those in need, all over the world.</p>
    <%= link_to "Create New", wikis_path, class: 'btn btn-primary' %>

  </div>
  <div class="col-md-4">
    <h2>Tell the World</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
     <%= link_to "Create New", wikis_path, class: 'btn btn-primary' %>
  </div>

  <div class="col-md-4">
    <h2>Prove It</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
     <%= link_to "Create New", wikis_path, class: 'btn btn-primary' %>
  </div>

<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset- col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                          
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Chip Neff 2015</p>
                </div>
            </div>
        </div>
    </footer>



</div>

app/views/wikis/_form.html.erb
<div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis:</p>
     <ol>
       <li>Be smart. Be clear.</li>
       <li>Be kind -- always be kind.</li>
       <li>Proofread, pretty-please.</li>
     </ol>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
        <% if current_user.private_allowed? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
        <% end %>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 
 <%= render partial: 'form', locals: { wiki: @wiki } %>
 </div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% if policy(Wiki.new).create? %>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>
<% @wikis.each do |wiki| %>
<div class="media">
     <div class="media-body">
       <h4 class="media-heading">
  <p><%= link_to wiki.title, wiki %></p>
   </h4>
     </div>
   </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
     
  <%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<% if policy(@wiki).edit? %>
  <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<% if policy(@wiki).destroy? %> 
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>

<% end %>


 <p><%= markdown_to_html @wiki.body %></p> 